# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data, Science, & Product
email: chris@chrisluiz.io
description: > # this means to ignore newlines until "baseurl:"
  A day by day account of Galvanize's Data Science Immersive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://CLuiz.github.io" # the base hostname & protocol for your site
twitter_username: CRLuiz
github_username:  CLuiz

# Build settings
markdown: kramdown
